### ISSUE TITLE
Path edit not working

### ISSUE THREAD

**Issue by itsmanojb** [suvadip172308/ui-excel#21]
URL: /dashboard/path/<pathId>?mode=display
Issue:
Hitting 'Done' button after editing does fire up the API (with 200) but message comes:
<pre>
error: {message: "Id not found"}
</pre>
And the details of path doesn't update.

**Comment by suvadip172308** [comment]
@itsmanojb Please test once. If it looks fine then close the issue.

**Comment by itsmanojb** [comment]
> @itsmanojb Please test once. If it looks fine then close the issue.

It seems, that reason we discussed, about incorrect path id, is solved on 74d2213
Created two test paths and those paths in fact are editable.

Closing it.
